(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.myself = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(5,1,1).p("AhtyAQATgKAVgNQAIgFAIgGQAbgTAegbQA7goBSAAQAbAAALABQAVACAGAHQggA9h6AbQhCAMghAGQgCABgCAAQgJACgIACQgYAFgSAFQgNAFgKAEAhPzGQgThuBggrQBVgmB1AfAkrqWQAtgpBNgxQAMgIBqg+ICVAAQAAAJAFAOQAFAOAAANQAABci4AYQgpAGhlAGQgtADgZAEQgQACgHADAhPniQg/AAhiAPQhiAPhHAAQgjAAghgCQjggOhjhyQhjh0AAkIQAAiIBiiJQA3hLBrhwQBRhjCuglQB0gYDCAAQFPAADICMQDRCSAAEDQAAEMkaCNQgpAVgxATIAAAAQhGAbhXAXQieAog+AQgAEspGQAzCKAZBRQAoCCAMBbQABAKABAKArPCTQAMAEFKDYQE+DQAjAAQCQAADckYQBBhRBQh3QAyhJARgXQAGgJACgCAGsiOQAvBCBNBLQBxBvCyCHQBnBPCpB3QBeBCC7CFQFNDuCZCbQDQDUAACoQAABGl2AqQh7AOipALQijAKgpADQjhARlSABQjvAAhKgIQgigEAAgGIAAAAQ6CgUq1AAQACgggPglQgPgkgCgcQgFARgFAQAk/xiIAKAAQAOAqAgBFQAeBDAOAqAqxvqQAehuAVgnQArhRBHAAQAgAAAlAdQASANAmAmAm3wcQhGAcgpAUQg3AcgdAgQgJALgGALQAagLAvgLQA7gOANgDQBNgXAIgwAnpmwIAKAAIAAFKQgkAjgEAWQgBAEABAvQAAAAAAABQAAAJAAALIgKAAAobAHQg0A0hgA+QgLAIgXANQAAAAgBAAQg0AghvBAQkrCti5CkQlSEriQCmQinDAg7CuQgBADgBADAFZYdIgBAAQgRAAgRAAQAAgNAIAEQAQAJAKAA");
	this.shape.setTransform(13,-40.5493);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AFTSrIABgKIgBAAQgKAAgQgJQgIgEAAANQ6CgUq1AAQACgggPglQgPgkgCgcIACgGQA7iuCnjAQCQimFSkrQC5ikErisICjhgIABAAIACAFQAMAEFKDYQE+DPAjAAQCPAADdkXQBAhRBRh3IBChhQByBxCxCGQBoBPCoB2IEaDHQFNDuCYCbQDRDUAACoQAABGl3AqQh6AOipALIjMANQjhARlTABIgTAAQjeAAhHgIgAkwwSQAtgpBNgxIB2hGICVAAQAAAJAFAOQAFAOAAANQAABci4AYQgpAGhlAGQgtADgZAEg");
	this.shape_1.setTransform(13.5125,-2.5493);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFF66").s().p("AkGNnQlKjYgMgEIgCgFIAjgVQBgg+Azg0IAUAAIAAAUIgKAAIAKAAIAAgUIAAgBQgBgwABgEQAEgWAkgjIAAlKIACgWQjggPhjhwQhjh0AAkIQAAiIBjiJQA2hLBrhwQBRhjCuglQB0gYDBAAQFPAADICMQDSCSAAEDQAAEMkaCNQgpAVgxASIAAAAQhGAbhXAYIjdA3IDdg3QBXgYBGgbIAAAAIACAHQAzCJAZBRQAoCBAMBcIACAUIgCgUQAvBBBMBMIhCBhQhRB3hABRQjdEYiQAAQgiAAk+jQgAkmAzQBHAABigPQBigPA+AAQg+AAhiAPQhiAPhHAAQgjAAghgCQAhACAjAAgAjMiAQAHgDAQgCQAZgEAugDQBkgGAogGQC5gYAAhcQAAgNgFgOQgFgOAAgJIiWAAIh1BGQhNAxgtApIADAZQgQACgHADgAjCpqQAOAqAgBFQAeBDAOAqQgOgqgehDQgghFgOgqIgKAAgAmyn0Qg4AcgdAgQgJALgGALQAbgLAugLIBIgRQBNgXAIgwQgIAwhNAXIhIARQguALgbALQAGgLAJgLQAdggA4gcQAogUBGgcQhGAcgoAUgAoLqHQgUAngfBuQAfhuAUgnQAshRBGAAQAgAAAlAdQASANAmAmQgmgmgSgNQglgdggAAQhGAAgsBRgACrqeIhkASIgEABIgRAEQgYAFgSAFIgWAJIAWgJQASgFAYgFIARgEIAEgBIBkgSQB6gbAgg9QgHgHgUgCQgLgBgbAAQhTAAg6AoQgfAagbAUIgagkIAKAuQgVAOgTAKQATgKAVgOIAQgKQAbgUAfgaQA6goBTAAQAbAAALABQAUACAHAHQggA9h6AbgAAjrOQgDgSAAgRQAAhSBRgkIAAAAIAGgDQAtgSA1AAIAAAAIAAAAQAqAAAwAMIAAAAIAEABIACAAIACABIgCgBIgCAAIgEgBIAAAAQgwgMgqAAIAAAAIAAAAQg1AAgtASIgGADIAAAAQhRAkAABSQAAARADASgAAtqgg");
	this.shape_2.setTransform(1.5,-90.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(5,1,1).p("AnflMQgPAAgOAAQg5AAg0gCQlrgPighxQihh0AAkIQAAiICgiJQBZhLCshwQCDhjEZglQC9gYE4AAQIfAAFDCMQFTCSAAEDQAAEMnJCNQhBAVhQATQhsAZiFAXQgHABgFABQkCAohkAQQhlAAieAPQiLANhqACIAABuQgkAjgEAWQgBAEABAwQAAAAAAABQAAAJAAALIgKAAAgWwIQAdgKAigNQAMgGAOgFQAsgUAygaQBegoCGAAQArAAASABQAiACAKAHQg0A9jFAbQhsAMg1AGQgEABgEAAQgOACgNACQgmAFgdAFQgVAEgQAFAAZxOQgehuCbgrQCLgmC9AfAlKoeQAmgVA0gYQAwgVA7gYQAUgICqg+IDzAAQAAAJAIAOQABABAAABQADAJADAIQABAEAAAEQAABckrAYQhBAGijAGQhLADgnAEAGLmkQAYBaAJBEQABAKABAKArPAbQAMAEFKDYQE+DQAjAAQCQAADckYQBBhRBQh2QAyhJARgYQAGgJACgCAGskGQAvBCBNBLQBxBwCyCGQBnBPCpB3QBeBCC7CFQFNDuCZCbQDQDUAACoQAABGl2AqQh7AOipALQijAKgpADQjhARlSABQjvAAhKgIQgigEAAgGIAAAAQ6CgUq1AAQACgggPglQgPgkgCgcQgFARgFAQAFZWlIgBAAQgRAAgRAAQAAgNAIAEQAQAJAKAAAotukQhxAchBAUQhbAcgtAgQgQALgJALQArgLBLgLQBfgOAVgDQB+gXAMgwAvBtyQAxhuAignQBGhRByAAQA0AAA8AdQAdANA9AmAlavqQAWAqA0BFQAxBDAWAqAobhwQg0A0hgA9QgLAIgXANQAAAAgBAAQg0AghvBAQkrCti5CkQlSEriQCmQinDAg7CuQgBADgBAD");
	this.shape_3.setTransform(13,-28.5493);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AFTQzIABgKIgBAAQgKAAgQgJQgIgEAAANQ6CgUq1AAQACgggPglQgPgkgCgcIACgGQA7iuCnjAQCQimFSkrQC5ijEritICjhgIABAAIACAFQAMAEFKDYQE+DPAjAAQCPAADdkXQBAhRBRh3IBChhQByBxCxCGQBoBPCoB3IEaDGQFNDuCYCbQDRDUAACoQAABGl3AqQh6AOipALIjMANQjhARlTABIgTAAQjeAAhHgIgAlPuaQAmgVA0gYQAwgVA7gYIC+hGIDzAAQAAAJAIAOIABACIAGARIABAIQAABckrAYQhCAGiiAGQhLADgnAEg");
	this.shape_4.setTransform(13.5125,9.4507);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFF66").s().p("AlZLvQlKjYgMgEIgDgFIAjgVQBgg+A0g0IAUAAIAAAUIgKAAIAKAAIAAgUIAAgBQgBgwABgEQAEgWAkgjIAAhvQBqgBCLgNQCegPBlAAIFlg4IAMgCIgMACIllA4QhlAAieAPQiLANhqABIgdABQg5AAg0gCQlrgPighxQihhzAAkIQAAiICgiJQBZhLCshwQCDhjEZglQC9gYE4AAQIeAAFECMQFTCSAAEDQAAEMnJCNQhCAUhPATQhsAZiGAXQAZBaAIBEIADAUIgDgUQAwBBBMBMIhCBhQhRB3hABRQjdEYiQAAQgiAAk+jQgAhliAQg7AXgwAWQg0AXgmAWIAFAZQAngEBLgDQCigGBCgGQErgYAAhcIgBgIIgGgRIgBgCQgIgOAAgJIjzAAIi+BGgAjwmDQAxBDAWAqQgWgqgxhDQg0hFgWgqQAWAqA0BFgAq/l8QhbAcgtAgQgQALgJALQArgLBLgLIB0gRQB+gXAMgwQgMAwh+AXIh0ARQhLALgrALQAJgLAQgLQAtggBbgcQBBgUBxgcQhxAchBAUgAtOoPQgiAngxBuQAxhuAignQBGhRByAAQA0AAA8AdQAdANA9AmQg9gmgdgNQg8gdg0AAQhyAAhGBRgAEVomIihASIgIABIgbAEQgnAFgdAFQgUAEgQAFQAQgFAUgEQAdgFAngFIAbgEIAIgBIChgSQDFgbA0g9QgLgHghgCQgTgBgqAAQiGAAhfAoQgxAagsAUIgqgkIAQAvQgiANgfAKQAfgKAigNIAagLQAsgUAxgaQBfgoCGAAQAqAAATABQAhACALAHQg0A9jFAbgAA5pWQgFgSAAgRQgBhSCDgkQBMgVBcAAIABAAIAAAAQBKAABUAOQhUgOhKAAIAAAAIgBAAQhcAAhMAVQiDAkABBSQAAARAFASgABJong");
	this.shape_5.setTransform(9.825,-78.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(5,1,1).p("Ao1jjQgPgBgOAAQldgPiahxQibh0AAkIQAAiICaiJQBVhLCmhwQB+hjEOglQC2gYEsAAQIKAAE3CMQFFCSAAEDQAAEMm3CNQg/AVhMATQhHARhSAQQgnAIgpAHQgFABgGABQj4AohgAQQhhAAiYAPQhxALhbADAgWueQAcgKAhgNQALgGAOgFQAqgUAwgaQBbgoCAAAQApAAASABQAgACAKAHQgyA9i9AbQhpAMgyAGQgEABgDAAQgOACgNACQglAFgbAFQgUAEgQAFAAXvkQgdhuCVgrQCGgmC1AfAk+m0QADgCACgBQAjgUAvgWQAtgWA5gXQATgICkg+IDqAAQAAAJAHAOQABABAAABQADAIAEAJQAAAEAAAEQAABNjLAeQgnAGgtADQhAAGicAGQhIADgmAEAF6k6QANAuAIApArPhOQAMAEFKDXQE+DQAjAAQCQAADckYQBBhQBQh3QAyhJARgYQAGgJACgCAHKlJQAoAxA2A1QBxBwCyCGQBnBPCpB3QBeBCC7CFQFNDuCZCbQDQDUAACoQAABGl2AqQh7AOipALQijAKgpADQjhARlSABQjvAAhKgIQgigEAAgGIAAAAQ6CgUq1AAQACgggPglQgPgkgCgcQgFARgFAQAFZU7IgBAAQgRAAgRAAQAAgNAIAEQAQAJAKAAAudsIQAvhuAhgnQBDhRBuAAQAyAAA6AdQAbANA7AmAlOuAQAWAqAyBFQAvBDAVAqAoYs6QhtAcg/AUQhXAcgsAgQgOALgKALQAqgLBIgLQBcgOAUgDQB4gXAMgwAobjaQg0A0hgA+QgLAIgXANQAAAAgBAAQg0AghvA/QkrCti5CkQlSEriQCmQinDAg7CuQgBADgBADAoHjjQAAAEAAAEQAAAAAAABQAAAJAAALIgKAA");
	this.shape_6.setTransform(13,-17.9493);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AFTPJIABgKIgBAAQgKAAgQgJQgIgEAAANQ6CgUq1AAQACgggPglQgPgkgCgcIACgGQA7iuCnjAQCQimFSkqQC5ikEritICjhgIABAAIACAFQAMAEFKDYQE+DQAjAAQCPAADdkYQBAhRBRh3IBChhQByBxCxCGQBoBPCoB3IEaDGQFNDuCYCbQDRDUAACoQAABGl3AqQh6AOipALIjMANQjhARlTABIgTAAQjeAAhHgIgAlDswIAFgDQAjgUAvgWQAtgWA5gXIC3hGIDpAAQAAAJAIAOIABACIAGARIABAIQAABNjLAeQgnAGguADQg/AGicAGQhIADgmAEg");
	this.shape_7.setTransform(13.5125,20.0507);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFF66").s().p("AlZKFQlKjYgMgEIgDgFIAjgVQBgg+A0g0IAUAAIAAAUIgKAAIAKAAIAAgUIAAgBIAAgIIguAAIgdgBQldgPiahxQibh0AAkHQAAiICaiJQBVhLCmhwQB+hjEOglQC2gYErAAQIKAAE3CMQFGCSAAEDQAAEMm3CMQg/AVhNATQhGARhSAQIhQAPIgMACIlXA4QhhAAiYAPQhxALhbADQBbgDBxgLQCYgPBhAAIFXg4IAMgCIBQgPQAnAwA2A2IhCBhQhRB3hABRQjdEYiQAAQgiAAk+jQgAGvEUQgJgpgMguQAMAuAJApgAhhgWQg5AWgtAWQgvAWgjAUIgFADIAEAZQAmgEBIgDQCcgGA/gGQAugEAngFQDLgeAAhMIgBgIIgGgRIgBgCQgIgOAAgJIjpAAIi3BGgAjmkZQAvBDAVAqQgVgqgvhDQgyhFgWgqQAWAqAyBFgAqkkSQhXAcgsAgQgOALgKALQAqgLBIgLIBwgRQB4gXAMgwQgMAwh4AXIhwARQhIALgqALQAKgLAOgLQAsggBXgcQA/gUBtgcQhtAcg/AUgAstmlQghAngvBuQAvhuAhgnQBDhRBuAAQAyAAA6AdQAbANA7AmQg7gmgbgNQg6gdgyAAQhuAAhDBRgAELm8IicASIgHABIgaAEQglAFgdAFQgTAEgPAFQAPgFATgEQAdgFAlgFIAagEIAHgBICcgSQC9gbAyg9QgKgHghgCQgRgBgpAAQiBAAhbAoQgvAagrAUIgogkIAPAvQghANgdAKQAdgKAhgNIAZgLQArgUAvgaQBbgoCBAAQApAAARABQAhACAKAHQgyA9i9AbgAA3nsQgFgTAAgQQAAhSB9gkIAGgBQBHgUBVAAIABAAIAAAAQBHAABRAOQhRgOhHAAIAAAAIgBAAQhVAAhHAUIgGABQh9AkAABSQAAAQAFATgABGm9g");
	this.shape_8.setTransform(9.825,-68.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(5,1,1).p("AnflMQgPAAgOAAQg5AAg0gCQlrgPighxQihh0AAkIQAAiICgiJQBZhLCshwQCDhjEZglQC9gYE4AAQIfAAFDCMQFTCSAAEDQAAEMnJCNQhBAVhQATQhsAZiFAXQAZBaAIBEQABAKABAKAgWwIQAdgKAigNQAMgGAOgFQAsgUAygaQBegoCGAAQArAAASABQAiACAKAHQg0A9jFAbQhsAMg1AGQgEABgEAAQgOACgNACQgmAFgdAFQgVAEgQAFAAZxOQgehuCbgrQCLgmC9AfAGLmkQgGABgGABQkCAohkAQQhlAAieAPQiLANhqACIAABuQgkAjgEAWQgBAEABAwQAAAAAAABQAAAJAAALIgKAAAlKoeQAmgWA0gXQAwgWA7gXQAUgICqg+IDzAAQAAAJAIAOQABABAAABQADAIAEAJQAAAEAAAEQAABckrAYQhBAGijAGQhLADgnAEAIoh5QAHgKABgBArPAbQAMAEFKDYQE/DQAiAAQCQAADckYQBBhRBQh2QAyhKARgXAGskGQAwBBBMBMQByBwCxCGQBnBPCpB3QBeBCC7CFQFNDuCZCbQDQDUAACoQAABGl2AqQh7AOipALQijAKgpADQjhARlSABQjvAAhKgIQgigEAAgGIAAAAQAAgOAIAFQARAJAKAAQgSAAgRAAQ6DgUq0AAQACgggPglQgQgkgBgcQgGAQgEARAFZWlIAAAAAvBtyQAxhuAignQBGhRByAAQA0AAA8AdQAdANA9AmAotukQhxAchBAUQhbAcgtAgQgQALgJALQArgLBLgLQBfgOAVgDQB+gXAMgwAlavqQAWAqA0BFQAxBDAWAqAobhwQg0A0hgA9QgMAHgWAOIgBAAQg1AghuBAQkrCti5CkQlSEriQCmQinDAg7CuQgBADgBAD");
	this.shape_9.setTransform(14,-26.9986);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("AFTQzIABgKIgBAAQgKAAgQgJQgIgFAAAOQ6DgUq0AAQACgggPglQgQgkgBgcIACgGQA7iuCnjAQCQimFSkrQC5ijEritICjhgIABAAIACAFQAMAEFKDYQE+DPAjAAQCPAADdkXQBAhRBRh3IBChhQByBwCxCHQBoBPCoB3IEaDGQFNDuCYCbQDRDUAACoQAABGl3AqQh6AOipALIjMANQjhARlTABIgaAAQjYAAhGgIgAlPuaQAmgWA0gXQAwgWA7gXIC+hGIDzAAQAAAJAIAOIABACIAGARIABAIQAABckrAYQhCAGiiAGQhLADgnAEg");
	this.shape_10.setTransform(14.525,11.0014);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFF66").s().p("AlZLvQlKjYgMgEIgCgFIAigVQBgg+A0g0IAUAAIAAAUIgKAAIAKAAIAAgUIAAgBQgBgwABgEQAEgWAkgjIAAhuQBqgCCLgNQCegPBlAAIFlg4IAMgCIgMACIllA4QhlAAieAPQiLANhqACIgdAAQg5AAg0gCQlrgPighxQihhzAAkIQAAiICgiJQBZhLCshwQCDhjEZglQC9gYE4AAQIeAAFECMQFTCSAAEDQAAEMnJCNQhCAUhPATQhsAZiGAXQAZBaAJBEQAvBBBMBMIhCBhQhRB3hABRQjdEYiQAAQgiAAk+jQgAHOEFIgCgUIACAUgAhliAQg7AXgwAWQg0AXgmAWIAFAZQAngEBLgDQCigGBCgGQErgYAAhcIgBgIIgGgRIgBgCQgIgOAAgJIjzAAIi+BGgAjwmDQAxBDAWAqQgWgqgxhDQg0hFgWgqQAWAqA0BFgAq/l8QhbAcgtAgQgQALgJALQArgLBLgLIB0gRQB+gXAMgwQgMAwh+AXIh0ARQhLALgrALQAJgLAQgLQAtggBbgcQBBgUBxgcQhxAchBAUgAtOoPQgiAngxBuQAxhuAignQBGhRByAAQA0AAA8AdQAdANA9AmQg9gmgdgNQg8gdg0AAQhyAAhGBRgAEVomIihASIgIABIgbAEQgnAFgdAFQgUAEgQAFQAQgFAUgEQAdgFAngFIAbgEIAIgBIChgSQDFgbA0g9QgLgHghgCQgTgBgqAAQiGAAhfAoQgxAagsAUIgqgkIAQAvQgiANgfAKQAfgKAigNIAagLQAsgUAxgaQBfgoCGAAQAqAAATABQAhACALAHQg0A9jFAbgAA5pWQgFgSAAgRQgBhSCDgkIABAAIACgBIABAAIADgBQBKgTBYAAIAAAAIAAAAQBIAABSANIAEABIgEgBQhSgNhIAAIAAAAIAAAAQhYAAhKATIgDABIgBAAIgCABIgBAAQiDAkABBSQAAARAFASgABJong");
	this.shape_11.setTransform(10.825,-77.375);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(5,1,1).p("AhtyAQATgKAVgNQAHgGAJgFQAbgUAegaQA7goBSAAQAbAAALABQAVACAGAHQggA9h6AbQhCAMghAGQgCABgCAAQgJACgIACQgYAFgSAFQgNAEgKAFAhPzGQgThuBggrQBVgmB1AfAkrqWQAtgpBNgxQAMgIBqg+ICVAAQAAAJAFAOQAFAOAAANQAABci4AYQgpAGhlAGQguADgYAEQgQACgHADAhPniQg/AAhiAPQhiAPhHAAQgjAAghgCQjggPhjhxQhjh0AAkIQAAiIBiiJQA3hLBrhwQBRhjCuglQB0gYDCAAQFPAADICMQDRCSAAEDQAAEMkaCNQgpAVgxATQhGAahXAYQieAog+AQgAGsiOQABAKABAKAEspGQAzCKAZBRQApCBALBcQAwBBBMBMQByBvCxCHQBnBPCpB3QBeBCC7CFQFNDuCZCbQDQDUAACoQAABGl2AqQh7AOipALQijAKgpADQjhARlSABQjvAAhKgIQgigEAAgGIAAAAQAAgOAIAFQARAJAKAAQgSAAgRAAQ6DgUq0AAQACgggPglQgQgkgBgcQgGAQgEARAIogBQAHgKABgBArPCTQAMAEFKDYQE+DQAjAAQCQAADckYQBBhRBQh3QAyhKARgWAFZYdIAAAAAqxvqQAehuAVgnQArhRBHAAQAgAAAlAdQASANAmAmAk/xiIAKAAQAOAqAgBFQAeBDAOAqAm3wcQhGAcgpAUQg4AcgcAgQgJALgGALQAagLAvgLQA7gOANgDQBNgXAIgwAnpmwIAKAAIAAFKQgkAjgEAWQgBAEABAvQAAAAAAABQAAAJAAALIgKAAAobAHQg0A0hgA+QgMAHgWAOIgBAAQg1AghuBAQkrCti5CkQlSEriQCmQinDAg7CuQgBADgBAD");
	this.shape_12.setTransform(13,-38.0486);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF0000").s().p("AFTSrIABgKIgBAAQgKAAgQgJQgIgFAAAOQ6DgUq0AAQACgggPglQgQgkgBgcIACgGQA7iuCnjAQCQimFSkrQC5ikErisICjhgIABAAIACAFQAMAEFKDYQE+DPAjAAQCPAADdkXQBAhRBRh3IBChhQByBwCxCHQBoBPCoB2IEaDHQFNDuCYCbQDRDUAACoQAABGl3AqQh6AOipALIjMANQjhARlTABIgaAAQjYAAhGgIgAkwwSQAtgpBNgxIB2hGICVAAQAAAJAFAOQAFAOAAANQAABci4AYQgpAGhlAGQguADgYAEg");
	this.shape_13.setTransform(13.525,-0.0486);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFF66").s().p("AkGNnQlKjYgMgEIgCgFIAjgVQBgg+Azg0IAUAAIAAAUIgKAAIAKAAIAAgUIAAgBQgBgwABgEQAEgWAkgjIAAlKIADgWQjhgPhjhwQhjh0AAkIQAAiIBjiJQA2hLBrhwQBRhjCuglQB0gYDBAAQFPAADICMQDSCSAAEDQAAEMkaCNQgpAVgxATQhGAahXAYIjdA3IDdg3QBXgYBGgaIACAGQAzCJAZBRQApCBALBcIACAUIgCgUQAwBBBLBMIhCBhQhRB3hABRQjdEYiQAAQgiAAk+jQgAkmAzQBHAABigPQBigPA+AAQg+AAhiAPQhiAPhHAAQgjAAgggCQAgACAjAAgAjMiAQAHgDAQgCQAYgEAvgDQBkgGAogGQC5gYAAhcQAAgNgFgOQgFgOAAgJIiWAAIh1BGQhNAxgtApIADAZQgQACgHADgAjCpqQAOAqAgBFQAeBDAOAqQgOgqgehDQgghFgOgqIgKAAgAmyn0Qg4AcgdAgQgJALgGALQAbgLAugLIBIgRQBNgXAIgwQgIAwhNAXIhIARQguALgbALQAGgLAJgLQAdggA4gcQAogUBGgcQhGAcgoAUgAoLqHQgUAngfBuQAfhuAUgnQAshRBGAAQAgAAAlAdQASANAmAmQgmgmgSgNQglgdggAAQhGAAgsBRgACrqeIhkASIgEABIgRAEQgYAFgSAFQgMAEgKAFQAKgFAMgEQASgFAYgFIARgEIAEgBIBkgSQB6gbAgg9QgHgHgUgCQgLgBgbAAQhTAAg6AoQgfAagbAUQAbgUAfgaQA6goBTAAQAbAAALABQAUACAHAHQggA9h6AbgAAFqIQATgKAVgNIAQgLIgagkIAKAvQgVANgTAKgAAjrOQgDgSAAgRQAAhSBRgkIAAAAIAEgCQAugTA2AAIAAAAIAAAAQAtAAAyANIADABIgDgBQgygNgtAAIAAAAIAAAAQg2AAguATIgEACIAAAAQhRAkAABSQAAARADASg");
	this.shape_14.setTransform(1.5,-88.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},4).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},4).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9}]},5).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},5).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-198.5,-201.3,424,324.1);


(lib.flagbutton = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(5,1,1).p("AAUjRQgUAUhmBLQhQA5gbAwQBCAVCNBOQCWBVA+AZIAAAK");
	this.shape.setTransform(181,70);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(5,1,1).p("AgJi4IAJAAIAAFxIAKAA");
	this.shape_1.setTransform(160,61.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(5,1,1).p("AAUh3IgxAAQgnAmgOAWQgbAmAAApQAAA9AUATQAVAUBEAAQAZAAAkgUQAfgTASgV");
	this.shape_2.setTransform(138,73);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(5,1,1).p("AAAh3IAADv");
	this.shape_3.setTransform(106,73);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(5,1,1).p("AgDgOIAAAdQAFgIABgCQABgCgHgRg");
	this.shape_4.setTransform(103.3556,49.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(5,1,1).p("AgJipQAFA3AEByQAFBzAFA3");
	this.shape_5.setTransform(90,65);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(5,1,1).p("ADNh9IkhAAQgpAXgcAVQgzAnAAA4QAABKBnAaQBLASB5gI");
	this.shape_6.setTransform(53.5,69.6338);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(5,1,1).p("ApkhsQgCgYAAgaQAAjFBthnQBshkDLAAQD9AACIB5QCMB8AAD1QAAASgBARQAGgDAGgEQAdgQAKgMApkhsIA6AAQBcBaCyAAQAzAAAggiQAUgWAXg2QAYg5AOgSQAbgjAsAAQAcAAAiAjQAsAwAYAbQBkBuBjAAQAXAAAfgPQgODAivBjQiRBSjWABQgeAAgegBA/KuDMA+VAAAIAAcHMg+VAAAgAheEYQgSAHgqAHQgoAGgUAAQivAAh0iMQhehzgNiZ");
	this.shape_7.setTransform(12.5,12.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0000FF").s().p("AhLD5QAVgBAogGQApgHARgHQgRAHgpAHQgoAGgVABQiugBh0iMQhehxgNiaIA5AAQBdBaCxAAQA0AAAggjQAUgVAWg2QAYg5AOgSQAbgjArAAQAdAAAjAjIBEBLQBjBuBkAAQAXAAAegPQgNDAivBjQiSBSjWABg");
	this.shape_8.setTransform(-1.45,17.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0000").s().p("ADdCgIhDhLQgkgjgcAAQgsAAgbAjQgOASgXA5QgWA2gVAVQgfAjg0AAQiyAAhchaIg6AAQgCgZAAgZQAAjFBthmQBshkDLAAQD9AACIB5QCMB8AAD0IgBAjQgfAPgXAAQhjAAhkhug");
	this.shape_9.setTransform(-1.5,-16.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("A/KOEIAA8HMA+VAAAIAAcHgAjWFVQDWgBCRhSQCvhjAOjAIAMgHQAdgQAKgMQgKAMgdAQIgMAHIABgjQAAj1iMh8QiIh5j9AAQjLAAhsBkQhtBnAADFQAAAaACAYQANCZBeBzQB0CMCvAAIAAApIg8gBIA8ABIAAAAg");
	this.shape_10.setTransform(12.5,12.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#000000").ss(5,1,1).p("AgxjaIiCAAQhHAugaAZQgrAoAABIQAAA4BaAmQBIAeA/AAQBKAAAPhAQAEgUADgxQADg4AFgeQgCA/CGB/QBGBDBsBc");
	this.shape_11.setTransform(161,19.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(5,1,1).p("AgJgxQAJAAAPAFQARAFANAAQAeAAAFgUQAAgbAAgNQAAg2gegQQgRgKgvAAQg8AAgtA7QgoA2AAA5QAAA/BkBCQBbA8A/AAQAuAAAHgWQAEgiAIgY");
	this.shape_12.setTransform(99,19);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#000000").ss(5,1,1).p("AgJEmQgBhOgEh6QgFioAAhUICLAAAgJEmQABAegBAZAh3lcQAHBQA6EMQAnCzAGBz");
	this.shape_13.setTransform(75,7.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#000000").ss(5,1,1).p("ABzlDQgXAXjpCKQjfCNAAA8QAAA3FqB4QByAmCHAnQBsAgAKAB");
	this.shape_14.setTransform(-131.5,17.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(5,1,1).p("Agxo4QAABlAuHkQAgFuAVC6");
	this.shape_15.setTransform(-162,16.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(5,1,1).p("AgJEmQgBhOgEh6QgFioAAhUICLAAAh3lcQAHBQA6EMQAnCzAGBzQABAegBAZ");
	this.shape_16.setTransform(75,7.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(5,1,1).p("ApkhsQgCgYAAgaQAAjFBthnQBshkDLAAQD9AACIB5QCMB8AAD1QAAASgBARQAGgDAGgEQAdgQAKgMApkhsIA6AAQBcBaCyAAQAzAAAggiQAUgWAXg2QAYg5AOgSQAbgjAsAAQAcAAAiAjQAsAwAYAbQBkBuBjAAQAXAAAfgPQgODAivBjQiRBSjWABQgeAAgegBA/KuDQekE2fxk2IAAcHQ/Lm4/KG4gAheEYQgSAHgqAHQgoAGgUAAQivAAh0iMQhehzgNiZ");
	this.shape_17.setTransform(12.5,12.025);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#CCCCCC").s().p("A/KOEIAA8HQekE2fxk2IAAcHQ/Lm4/KG4gAjWFVQDWgBCRhSQCvhjAOjAIAMgHQAdgQAKgMQgKAMgdAQIgMAHIABgjQAAj1iMh8QiIh5j9AAQjLAAhsBkQhtBnAADFQAAAaACAYQANCZBeBzQB0CMCvAAIAAApIg8gBIA8ABIAAAAg");
	this.shape_18.setTransform(12.5,12.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_10},{t:this.shape_7},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]},1).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_18},{t:this.shape_17},{t:this.shape_15},{t:this.shape_14},{t:this.shape_16},{t:this.shape_12},{t:this.shape_11}]},1).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_10},{t:this.shape_7},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-189.5,-80.4,404,184.9);


(lib.ciclebutton = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.text = new cjs.Text("click", "bold 40px 'Arial'");
	this.text.textAlign = "center";
	this.text.lineHeight = 47;
	this.text.lineWidth = 253;
	this.text.parent = this;
	this.text.setTransform(41.5,-34.7);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A7BryMA2DAAAIAAXlMg2DAAAg");
	this.shape.setTransform(40,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A7BLzIAA3lMA2DAAAIAAXlg");
	this.shape_1.setTransform(40,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#66FFFF").s().p("A7BLzIAA3lMA2DAAAIAAXlg");
	this.shape_2.setTransform(40,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF6600").s().p("A7BLzIAA3lMA2DAAAIAAXlg");
	this.shape_3.setTransform(40,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.text,p:{color:"#000000"}}]}).to({state:[{t:this.shape_2},{t:this.shape},{t:this.text,p:{color:"#003366"}}]},1).to({state:[{t:this.shape_3},{t:this.shape},{t:this.text,p:{color:"#990000"}}]},1).to({state:[{t:this.shape_1},{t:this.shape},{t:this.text,p:{color:"#000000"}}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-134,-76.5,348,153);


(lib.carl = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(5,1,1).p("AI0zJQBChoAjgkQBPhQBkAAQBFAABvCqQBuCoAABmQAAA2gUAkQgXAogqAAQgtAAhmg8Qhmg8gQAAQgEAAgNAHQgIAFgKAGQgjAVAAABAkuBkQguiQgZhZQgWhPgNhHQgRhgAAhRQAAiIBCiWQADgGADgHQA1h1BUhoQAPgSAQgSQBwh/CEhJQCOhPCKAAQBpAABvBRQAbAUAbAYQBSBKBMBsQAnA5AmBCQBoC1A/DJQA/DLAACZQAADLiqB/QgPALgPAKQgBA+gOBuQgBAIgBAJQgQBzADBAAK2svIAAgKIhGAAQAAADgFALQgFALAAAPQAAAeAUAUIBGAAQAAgOAFggQAFghAAgVAKaurQhZAWg2BCQg7BHAABpQAAA3AyAZQAoAUBGAAQCgAAAAigQAAgsgXguQgHgPgKgQQgHgLgJgMQgTgagWgSQgKgJgLgHQgqgbgyABIAAgKAhfo/QgIgegGgpQgFgegBgTQAAgFAAgFQAAg+AygwQAzgyBEAAQBnAAA5BGQAyA9AABeQAABCgyASQgdALhlAAQgoAAg4gPQg5gPgaAAgAIiirQgFgGgJAFQgJAFgOAAQgpAAg2hGQgyhBAAghQAAg+BGgcQAxgUBHAAQBDAAAXAeQAUAaAABFQAABKgtAlQgZAWgwAQQgYAIgcAGAbQUWQgGACgFACQiQAzj2AUQhmAJh2ADQikAEoDgLQiHgCjEATQhuAKjGAXQiJAOkUAAQiLgBiAgDInCAAQhZAAhrgkQiMgvgigHIAAhkQAFgFAFgVQAAgDABgDQAFgUAEgIAOIGSQA+AsC2B+QCsB6B0BmQFUEoggDIQgGADgJADQgJACgMACQgfAGgNAEAKrBeQgCAUgBARQgEB6BjAWQhNAfhaAKQgyAGg2AAQiFAAhpgXQhPgShigpQhvgxhDgZQhngnhugbQgRgEgQgEAKYBSQADAaAAAXQACA8gQAxQgQAvgdAdQgPAQgTAKANqDgQgvAeg0AVAHaOaQAmAdAiBdQAkBigIBGAK2NeQAQgOAxgEQATgCApAAQCUAACjCjQB5B5BTCcAjrvjQgtgOhugvQhmgng6AAQhuAAhCBaQg7BRAAByQAAA2ATAVQAUAUAzAAQAyAAA6gjQA6gjBKAAQAvAAArAUAhVq3QAIgMAagSQAcgUANAAQANAAAJAFQAJAFADAAQAAAUgBAJQgDAOgGAHIg7AAIAAgUAkdCYQgJgbgIgZAm9kTQgcAtgrA0QgZAdgyA5QhZBrgjBrQgPAtgRBvQgGAigFAoQgVCWguBkAsREQQg6BvjACDQgzAjhjA/QhSA3gmAjQh6ByhSB0QhfCIgzCaIgKAAAtNQwQBLhzCAgyQBzgtC2AAQBmAACVAVQDEAbAgACA7RTaQAZgBARgKQAKgGAJgFQAJgEAGgDIAAAB");
	this.shape.setTransform(-7.3622,23.7509);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC00").s().p("AE/IoQAQgygBg7IANAAQgFB6BjAWQhNAehaALQAdgdAQgvgABQBKQgyhBAAggQAAg+BGgcQAxgUBHAAQBDAAAXAeQAUAaAABFQAABJgtAlQgYAVgxARQgFgGgJAFQgJAFgOAAQgpAAg2hGgAlaj4Qg5gPgaAAQgHgegHgpQgEgfgCgSIAAgKQAAg+AygwQA0gyBEAAQBnAAA5BGQAyA9AABeQAABCgyASQgdALhlAAQgoAAg5gPgAl7l1IA8AAQAHgHACgOIABgdQgDAAgJgFQgJgFgOAAQgNAAgbAUQgaASgJAMQAJgMAagSQAbgUANAAQAOAAAJAFQAJAFADAAIgBAdQgCAOgHAHIg8AAIAAgUIAAAUgAC0kbQgygZAAg3QAAhpA7hHQA2hCBZgWQALAHALAIQAVATATAaIAQAXQAKAPAIAQQAWAtAAAtQAACgigAAQhGAAgogUgAEYnZQAAAeAUAUIBGAAQAAgOAFggQAFghAAgVQAAAVgFAhQgFAgAAAOIhGAAQgUgUAAgeQAAgPAFgLQAFgLAAgDIBGAAIAAAKIAAgKIhGAAQAAADgFALQgFALAAAPIAAAAg");
	this.shape_1.setTransform(26,-7.4125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("Ap5WmQiLgBiAgDInCAAQhZAAhrgkQiMgvgigHIAAhkQAFgFAFgVIABgGIAPgHIAAABIAEAIIAKAAQAziaBfiIQBSh0B6hyQAmgjBSg3QBjg/AzgjQDAiDA6hvIAmAGIgLBKQgVCWguBkQAuhkAViWIALhKQARhvAPgtQAjhrBZhrIBLhWQArg0AcgtIAlgIQANBHAWBPQAZBZAuCQQguiQgZhZQgWhPgNhHQgRhgAAhRQAAiIBCiWIAGgNQA1h1BUhoIAfgkQBwh/CEhJQCOhPCKAAQBpAABvBRIAJgLQBChoAjgkQBPhQBkAAQBFAABvCqQBuCoAABmQAAA2gUAkQgXAogqAAQgtAAhmg8Qhmg8gQAAQgEAAgNAHQhMhshShKQgbgYgbgUQAbAUAbAYQBSBKBMBsQAnA5AmBCQBoC1A/DJQA/DLAACZQAADLiqB/IgeAVQgvAeg0AVQA0gVAvgeQgBA+gOBuIgCARQgOBjAAA9IABATIgBgTQAAg9AOhjIACgRIAtAGID0CqQCsB6B0BmQFUEoggDIQgGADgJADIAEAIQiQAzj2AUQhmAJh2ADQikAEoDgLQiHgCjEATQhtAKjHAXQiEAOkGAAIgTAAgAaTUWQgfAGgNAEQANgEAfgGIAVgEIgVAEgARRPtQB5B5BTCcQhTich5h5QijijiUAAQgpAAgTACQgxAEgQAOQAQgOAxgEQATgCApAAQCUAACjCjgAIlS8IABgaQAAg9gdhRQgihdgmgdQAmAdAiBdQAdBRAAA9IgBAagAqbOLQiAAyhLBzQBLhzCAgyQBzgtC2AAQBmAACVAVQDEAbAgACQgggCjEgbQiVgVhmAAQi2AAhzAtgAJHE8QgPAQgTAKQATgKAPgQQBagKBNgfQhjgWAEh6QABgRACgUQgCAUgBARIgNAAQAAgXgDgaQADAaAAAXQACA8gQAxQgQAvgdAdIAAAAgAHfFCQA2AAAygGQgyAGg2AAQiFAAhpgXQhPgShigpQhvgxhDgZQhngnhugbIghgIIAhAIQBuAbBnAnQBDAZBvAxQBiApBPASQBpAXCFAAIAAAAgAk2CYIgRg0IARA0gAIJirQgYAIgcAGQAcgGAYgIQAwgQAZgWQAtglAAhKQAAhFgUgaQgXgehDAAQhHAAgxAUQhGAcAAA+QAAAhAyBBQA2BGApAAQAOAAAJgFQAEgCADAAQAEAAADADgAhasvQgyAwAAA+IAAAKQABATAFAeQAGApAIAeQAaAAA5APQA4APAoAAQBlAAAdgLQAygSAAhCQAAhegyg9Qg5hGhnAAQhEAAgzAygAKBurQhZAWg2BCQg7BHAABpQAAA3AyAZQAoAUBGAAQCgAAAAigQAAgsgXguQgHgPgKgQIgQgXQgTgagWgSQgKgJgLgHIgCgBIgBgBIAAAAQgogYgvAAIAAAAIgCAAIAAgKIAAAKIACAAIAAAAQAvAAAoAYIAAAAIABABIACABgALUvRIgjAWIAjgWIASgLIgSALgAsXrfIgThLQAAhyA7hRQBChaBuAAQA6AABmAnQBuAvAtAOIATAPQhUBog1B1IgMgGQgrgUgvAAQhKAAg6AjQg6AjgyAAQgzAAgUgUg");
	this.shape_2.setTransform(-4.8622,23.7509);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(5,1,1).p("AI0zJQBChoAjgkQBPhQBkAAQBFAABvCqQBuCoAABmQAAA2gUAkQgXAogqAAQgtAAhmg8Qhmg8gQAAQgEAAgNAHQgIAFgKAGQgjAVAAABAkuBkQguiQgZhZQgWhPgNhHQgRhgAAhRQAAiIBCiWQADgGADgHQA1h1BUhoQAPgSAQgSQBwh/CEhJQCOhPCKAAQBpAABvBRQAbAUAbAYQBSBKBMBsQAnA5AmBCQBoC1A/DJQA/DLAACZQAADLiqB/QgPALgPAKQgBA+gOBuQgBAIgBAJQgQBzADBAAK2svIAAgKIhGAAQAAADgFALQgFALAAAPQAAAeAUAUIBGAAQAAgOAFggQAFghAAgVAKaurQhZAWg2BCQg7BHAABpQAAA3AyAZQAoAUBGAAQCgAAAAigQAAgsgXguQgHgPgKgQQgHgLgJgMQgTgagWgSQgKgJgLgHQgqgbgyABIAAgKAhfo/QgIgegGgpQgFgegBgTQAAgFAAgFQAAg+AygwQAzgyBEAAQBnAAA5BGQAyA9AABeQAABCgyASQgdALhlAAQgoAAg4gPQg5gPgaAAgAIiirQgFgGgJAFQgJAFgOAAQgpAAg2hGQgyhBAAghQAAg+BGgcQAxgUBHAAQBDAAAXAeQAUAaAABFQAABKgtAlQgZAWgwAQQgYAIgcAGAbQUWQgGACgFACQiQAzj2AUQhmAJh2ADQikAEoDgLQiHgCjEATQhuAKjGAXQiJAOkUAAQiLgBiAgDInCAAQhZAAhrgkQiMgvgigHIAAhkQAFgFAFgVQAAgDABgDQAFgUAEgIAOIGSQA+AsC2B+QCsB6B0BmQFUEoggDIQgGADgJADQgJACgMACQgfAGgNAEAKrBeQgCAUgBARQgEB6BjAWQgnAPgqALQgqAKgsAFQgPAQgTAKAKYBSQADAaAAAXQACA8gQAxQgQAvgdAdQgpAFgsABQgJAAgKAAQiFAAhpgXQhPgShigpQhvgxhDgZQhngnhugbQgRgEgQgEAILFCQADA3AsA1QA0A+A+AAQBGAAAjhSQAghJgRhLQgPAHgOAGAK2EkQAAAFAAAEQAABTAKAcAIMEuQgBAKAAAKANqDgQgiAWgkAQAHaOaQAmAdAiBdQAkBigIBGAK2NeQAQgOAxgEQATgCApAAQCUAACjCjQB5B5BTCcAjrvjQgtgOhugvQhmgng6AAQhuAAhCBaQg7BRAAByQAAA2ATAVQAUAUAzAAQAyAAA6gjQA6gjBKAAQAvAAArAUAhVq3QAIgMAagSQAcgUANAAQANAAAJAFQAJAFADAAQAAAUgBAJQgDAOgGAHIg7AAIAAgUAkdCYQgJgbgIgZAm9kTQgcAtgrA0QgZAdgyA5QhZBrgjBrQgPAtgRBvQgGAigFAoQgVCWguBkAsREQQg6BvjACDQgzAjhjA/QhSA3gmAjQh6ByhSB0QhfCIgzCaIgKAAAtNQwQBLhzCAgyQBzgtC2AAQBmAACVAVQDEAbAgACA7RTaQAZgBARgKQAKgGAJgFQAJgEAGgDIAAAB");
	this.shape_3.setTransform(-7.3622,23.7509);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AhgA1Qgrg1gDg2QArgBApgFQgPAPgTALQATgLAPgPQAtgFAogLQABBSAJAdQgJgdgBhSQAqgKAngQIAdgMQARBLgfBIQgjBShHAAQg9AAg0g+g");
	this.shape_4.setTransform(59.2854,61.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFCC00").s().p("AE/IoQAQgygBg7IANAAQgFB6BjAWQgnAPgqAKIAAgIIAAAIQgpALgtAFQAdgdAQgvgABQBKQgyhBAAggQAAg+BGgcQAxgUBHAAQBDAAAXAeQAUAaAABFQAABJgtAlQgYAVgxARQgFgGgJAFQgJAFgOAAQgpAAg2hGgAlaj4Qg5gPgaAAQgHgegHgpQgEgfgCgSIAAgKQAAg+AygwQA0gyBEAAQBnAAA5BGQAyA9AABeQAABCgyASQgdALhlAAQgoAAg5gPgAl7l1IA8AAQAHgHACgOIABgdQgDAAgJgFQgJgFgOAAQgNAAgbAUQgaASgJAMQAJgMAagSQAbgUANAAQAOAAAJAFQAJAFADAAIgBAdQgCAOgHAHIg8AAIAAgUIAAAUgAC0kbQgygZAAg3QAAhpA7hHQA2hCBZgWQALAHALAIQAVATATAaIAQAXQAKAPAIAQQAWAtAAAtQAACgigAAQhGAAgogUgAEYnZQAAAeAUAUIBGAAQAAgOAFggQAFghAAgVQAAAVgFAhQgFAgAAAOIhGAAQgUgUAAgeQAAgPAFgLQAFgLAAgDIBGAAIAAAKIAAgKIhGAAQAAADgFALQgFALAAAPIAAAAg");
	this.shape_5.setTransform(26,-7.4125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#666666").s().p("Ap5WmQiLgBiAgDInCAAQhZAAhrgkQiMgvgigHIAAhkQAFgFAFgVIABgGIAPgHIAAABIAEAIIAKAAQAziaBfiIQBSh0B6hyQAmgjBSg3QBjg/AzgjQDAiDA6hvIAmAGIgLBKQgVCWguBkQAuhkAViWIALhKQARhvAPgtQAjhrBZhrIBLhWQArg0AcgtIAlgIQANBHAWBPQAZBZAuCQQguiQgZhZQgWhPgNhHQgRhgAAhRQAAiIBCiWIAGgNQA1h1BUhoIAfgkQBwh/CEhJQCOhPCKAAQBpAABvBRIAJgLQBChoAjgkQBPhQBkAAQBFAABvCqQBuCoAABmQAAA2gUAkQgXAogqAAQgtAAhmg8Qhmg8gQAAQgEAAgNAHQhMhshShKQgbgYgbgUQAbAUAbAYQBSBKBMBsQAnA5AmBCQBoC1A/DJQA/DLAACZQAADLiqB/IgeAVQgiAWgkAQIgdANQhjgWAEh6QABgRACgUQgCAUgBARIgNAAQAAgXgDgaQADAaAAAXQACA8gQAxQgQAvgdAdQgpAFgsABIAAgIIABgMIgBAMIAAAIQADA3AsA1QA0A+A+AAQBGAAAjhSQAghJgRhLQAkgQAigWQgBA+gOBuIgCARQgOBjAAA9IABATIgBgTQAAg9AOhjIACgRIAtAGID0CqQCsB6B0BmQFUEoggDIQgGADgJADIAEAIQiQAzj2AUQhmAJh2ADQikAEoDgLQiHgCjEATQhtAKjHAXQiEAOkGAAIgTAAgAaTUWQgfAGgNAEQANgEAfgGIAVgEIgVAEgARRPtQB5B5BTCcQhTich5h5QijijiUAAQgpAAgTACQgxAEgQAOQAQgOAxgEQATgCApAAQCUAACjCjgAIlS8IABgaQAAg9gdhRQgihdgmgdQAmAdAiBdQAdBRAAA9IgBAagAqbOLQiAAyhLBzQBLhzCAgyQBzgtC2AAQBmAACVAVQDEAbAgACQgggCjEgbQiVgVhmAAQi2AAhzAtgAhyCmQBDAZBvAxQBiApBPASQBpAXCFAAIATAAIgTAAQiFAAhpgXQhPgShigpQhvgxhDgZQhngnhugbQBuAbBnAngAk2CYIgRg0IARA0gAlHBkIghgIIAhAIgAIJirQgYAIgcAGQAcgGAYgIQAwgQAZgWQAtglAAhKQAAhFgUgaQgXgehDAAQhHAAgxAUQhGAcAAA+QAAAhAyBBQA2BGApAAQAOAAAJgFQAEgCADAAQAEAAADADgAhasvQgyAwAAA+IAAAKQABATAFAeQAGApAIAeQAaAAA5APQA4APAoAAQBlAAAdgLQAygSAAhCQAAhegyg9Qg5hGhnAAQhEAAgzAygAKBurQhZAWg2BCQg7BHAABpQAAA3AyAZQAoAUBGAAQCgAAAAigQAAgsgXguQgHgPgKgQIgQgXQgTgagWgSQgKgJgLgHIgCgBIgBgBIAAAAQgogYgvAAIAAAAIgCAAIAAgKIAAAKIACAAIAAAAQAvAAAoAYIAAAAIABABIACABgALUvRIgjAWIAjgWIASgLIgSALgAsXrfIgThLQAAhyA7hRQBChaBuAAQA6AABmAnQBuAvAtAOIATAPQhUBog1B1IgMgGQgrgUgvAAQhKAAg6AjQg6AjgyAAQgzAAgUgUg");
	this.shape_6.setTransform(-4.8622,23.7509);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(5,1,1).p("AI0zJQBChoAjgkQBPhQBkAAQBFAABvCqQBuCoAABmQAAA2gUAkQgXAogqAAQgtAAhmg8Qhmg8gQAAQgEAAgNAHQgIAFgKAGQgjAVAAABAkuBkQguiQgZhZQgWhPgNhHQgRhgAAhRQAAiIBCiWQADgGADgHQA1h1BUhoQAPgSAQgSQBwh/CEhJQCOhPCKAAQBpAABvBRQAbAUAbAYQBSBKBMBsQAnA5AmBCQBoC1A/DJQA/DLAACZQAADLiqB/QgPALgPAKQgiAWgkAQQgIAEgIADQgCgLgCgGIgKAAAK2svIAAgKIhGAAQAAADgFALQgFALAAAPQAAAeAUAUIBGAAQAAgOAFggQAFghAAgVAKaurQhZAWg2BCQg7BHAABpQAAA3AyAZQAoAUBGAAQCgAAAAigQAAgsgXguQgHgPgKgQQgHgLgJgMQgTgagWgSQgKgJgLgHQgqgbgyABIAAgKAhfo/QgIgegGgpQgFgegBgTQAAgFAAgFQAAg+AygwQAzgyBEAAQBnAAA5BGQAyA9AABeQAABCgyASQgdALhlAAQgoAAg4gPQg5gPgaAAgAIiirQgFgGgJAFQgJAFgOAAQgpAAg2hGQgyhBAAghQAAg+BGgcQAxgUBHAAQBDAAAXAeQAUAaAABFQAABKgtAlQgZAWgwAQQgYAIgcAGAbQUWQgGACgFACQiQAzj2AUIAAAAQgBAAgBAAQhlAJh1ADQikAEoDgLQiHgCjEATQhuAKjGAXQiJAOkUAAQiLgBiAgDInCAAQhZAAhrgkQiMgvgigHIAAhkQAFgFAFgVQAAgDABgDQAFgUAEgIAOIGSQA+AsC2B+QCsB6B0BmQFUEoggDIQgGADgJADQgJACgMACQgfAGgNAEAKYBSQADAaAAAXQACA8gQAxQgQAvgdAdQgpAFgsABAKrBeQgCAUgBARQgEB6BjAWQgnAPgqALQgqAKgsAFQgPAQgTAKAM4HiQgEgCgDgDQgWgSgDg4QgBgLABgOQABhNgFggQgHADgGADAK2EkQAAAFAAAEANqDgQgBA+gOBuQgBAIgBAJQgGAngDAhQgEApAAAfQgBATABAQAIMEuQgBAKAAAKQgJAAgKAAQiFAAhpgXQhPgShigpQhvgxhDgZQhngnhugbQgRgEgQgEAIMIeQAAhGABghQACgrAEgiQABgKACgKAIMIoQACA3AsA1QA0A+A+AAQBGAAAjhSQASgpACgqQACgggHghAK2ITQAABTAKAcAHaOaQAmAdAiBdQAkBigIBGAK2NeQAQgOAxgEQATgCApAAQCUAACjCjQB5B5BTCcAjrvjQgtgOhugvQhmgng6AAQhuAAhCBaQg7BRAAByQAAA2ATAVQAUAUAzAAQAyAAA6gjQA6gjBKAAQAvAAArAUAhVq3QAIgMAagSQAcgUANAAQANAAAJAFQAJAFADAAQAAAUgBAJQgDAOgGAHIg7AAIAAgUAkdCYQgJgbgIgZAm9kTQgcAtgrA0QgZAdgyA5QhZBrgjBrQgPAtgRBvIAAAAQgGAigFAoQgVCWguBkAsREQQg6BvjACDQgzAjhjA/QhSA3gmAjQh6ByhSB0QhfCIgzCaIgKAAAtNQwQBLhzCAgyQBzgtC2AAQBmAACVAVQDEAbAgACA7RTaQAZgBARgKQAKgGAJgFQAJgEAGgDIAAAB");
	this.shape_7.setTransform(-7.3622,23.7509);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("AhjCkQgsg1gCg2IAAgKQAAhGABghQACgrAEgiQgHgUgBgUQAsgBApgEQgPAPgTAKQATgKAPgPQAsgGApgKQAqgLAngPIANgGQAFAggBBNIAAAZQADA4AWASIgNAPQAHAggCAgQgCAqgSAqQgjBShGAAQg9AAg0g/gAAiCTQgKgdAAhTQAABTAKAdgAiKiFIADgUIgDAUg");
	this.shape_8.setTransform(59.6375,73.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#666666").s().p("Ap5WmQiLgBiAgDInCAAQhZAAhrgkQiMgvgigHIAAhkQAFgFAFgVIABgGIAPgHIAAABIAEAIIAKAAQAziaBfiIQBSh0B6hyQAmgjBSg3QBjg/AzgjQDAiDA6hvIAmAGIAAAAIgLBKQgVCWguBkQAuhkAViWIALhKIAAAAQARhvAPgtQAjhrBZhrIBLhWQArg0AcgtIAlgIQANBHAWBPQAZBZAuCQQguiQgZhZQgWhPgNhHQgRhgAAhRQAAiIBCiWIAGgNQA1h1BUhoIAfgkQBwh/CEhJQCOhPCKAAQBpAABvBRIAJgLQBChoAjgkQBPhQBkAAQBFAABvCqQBuCoAABmQAAA2gUAkQgXAogqAAQgtAAhmg8Qhmg8gQAAQgEAAgNAHQhMhshShKQgbgYgbgUQAbAUAbAYQBSBKBMBsQAnA5AmBCQBoC1A/DJQA/DLAACZQAADLiqB/IgeAVQgiAWgkAQQAkgQAigWQgBA+gOBuIgCARIgJBIQgEApAAAfIgBATIABAQIgBgQIABgTQAAgfAEgpIAJhIIACgRIAtAGID0CqQCsB6B0BmQFUEoggDIQgGADgJADIAEAIQiQAzj2AUIAAAAIgCAAQhlAJh1ADQikAEoDgLQiHgCjEATQhtAKjHAXQiEAOkGAAIgTAAgAaTUWQgfAGgNAEQANgEAfgGIAVgEIgVAEgARRPtQB5B5BTCcQhTich5h5QijijiUAAQgpAAgTACQgxAEgQAOQAQgOAxgEQATgCApAAQCUAACjCjgAIlS8IABgaQAAg9gdhRQgihdgmgdQAmAdAiBdQAdBRAAA9IgBAagAqbOLQiAAyhLBzQBLhzCAgyQBzgtC2AAQBmAACVAVQDEAbAgACQgggCjEgbQiVgVhmAAQi2AAhzAtgAJ0DwQgQAvgdAdQgpAFgsABQABAUAHAUQgEAigCArQgBAhAABGIAAAKQACA3AsA1QA0A+A+AAQBGAAAjhSQASgpACgqQACgggHghIANgPIAHAFIgHgFQgWgSgDg4QAchGgQhHIgQAHQgCgLgCgGIgKAAIAKAAQACAGACALIgNAGQhjgWAEh6QABgRACgUQgCAUgBARIgNAAQACA8gQAxgAhyCmQBDAZBvAxQBiApBPASQBpAXCFAAIATAAIAAgIIABgMIgBAMIAAAIIgTAAQiFAAhpgXQhPgShigpQhvgxhDgZQhngnhugbQBuAbBnAngAk2CYIgRg0IARA0gAKCCDQAAgXgDgaQADAaAAAXgAlHBkIghgIIAhAIgAHVidQAcgGAYgIQAwgQAZgWQAtglAAhKQAAhFgUgaQgXgehDAAQhHAAgxAUQhGAcAAA+QAAAhAyBBQA2BGApAAQAOAAAJgFQAJgFAFAGQgYAIgcAGgAhasvQgyAwAAA+IAAAKQABATAFAeQAGApAIAeQAaAAA5APQA4APAoAAQBlAAAdgLQAygSAAhCQAAhegyg9Qg5hGhnAAQhEAAgzAygAKBurQhZAWg2BCQg7BHAABpQAAA3AyAZQAoAUBGAAQCgAAAAigQAAgsgXguQgHgPgKgQIgQgXQgTgagWgSQgKgJgLgHIgCgBIgBgBIAAAAQgogYgvAAIAAAAIgCAAIAAgKIAAAKIACAAIAAAAQAvAAAoAYIAAAAIABABIACABgALUvRIgjAWIAjgWIASgLIgSALgAsXrfIgThLQAAhyA7hRQBChaBuAAQA6AABmAnQBuAvAtAOIATAPQhUBog1B1IgMgGQgrgUgvAAQhKAAg6AjQg6AjgyAAQgzAAgUgUg");
	this.shape_9.setTransform(-4.8622,23.7509);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(5,1,1).p("AI0zJQBChoAjgkQBPhQBkAAQBFAABvCqQBuCoAABmQAAA2gUAkQgXAogqAAQgtAAhmg8Qhmg8gQAAQgEAAgNAHQgIAFgKAGQgjAVAAABAkuBkQguiQgZhZQgWhPgNhHQgRhgAAhRQAAiIBCiWQADgGADgHQA1h1BUhoQAPgSAQgSQBwh/CEhJQCOhPCKAAQBpAABvBRQAbAUAbAYQBSBKBMBsQAnA5AmBCQBoC1A/DJQA/DLAACZQAADLiqB/QgPALgPAKQgBA+gOBuQgBAIgBAJQgBACAAABQgBAGAAAFQgBAJgBAIIgFAnAK2svIAAgKIhGAAQAAADgFALQgFALAAAPQAAAeAUAUIBGAAQAAgOAFggQAFghAAgVAKaurQhZAWg2BCQg7BHAABpQAAA3AyAZQAoAUBGAAQCgAAAAigQAAgsgXguQgHgPgKgQQgHgLgJgMQgTgagWgSQgKgJgLgHQgqgbgyABIAAgKAhfo/QgIgegGgpQgFgegBgTQAAgFAAgFQAAg+AygwQAzgyBEAAQBnAAA5BGQAyA9AABeQAABCgyASQgdALhlAAQgoAAg4gPQg5gPgaAAgAIiirQgFgGgJAFQgJAFgOAAQgpAAg2hGQgyhBAAghQAAg+BGgcQAxgUBHAAQBDAAAXAeQAUAaAABFQAABKgtAlQgZAWgwAQQgYAIgcAGAbQUWQgGACgFACQiQAzj2AUIAAAAQgBAAgBAAQgBABgCAAQhWAHhjADQgPABgPAAQikAEoDgLQiHgCjEATQhuAKjGAXQiJAOkUAAQiLgBiAgDInCAAQhZAAhrgkQiMgvgigHIAAhkQAFgFAFgVQAAgDABgDQAFgUAEgIAOIGSQA+AsC2B+QCsB6B0BmQFUEoggDIQgGADgJADQgJACgMACQgfAGgNAEAKYBSQADAaAAAXQACA8gQAxQgQAvgdAdQgpAFgsABQABAUAHAUQALAjAcAhQA0A+A+AAQBGAAAjhSQACgDABgEQABgDACgDQARgvgDgwQAAgCAAgCQAAgEgBgEQgBgOgDgOQgIAEgIADQgHADgGADQgnAPgqALQAABTAKAcAKrBeQgCAUgBARQgEB6BjAWAK2EkQAAAFAAAEQgqAKgsAFQgPAQgTAKAIMEuQgBAKAAAKQgJAAgKAAQiFAAhpgXQhPgShigpQhvgxhDgZQhngnhugbQgRgEgQgEANOIBQgCAYAAAUANqDgQgiAWgkAQAHaOaQAmAdAiBdQAkBigIBGAK2NeQAQgOAxgEQATgCApAAQCUAACjCjQB5B5BTCcAjrvjQgtgOhugvQhmgng6AAQhuAAhCBaQg7BRAAByQAAA2ATAVQAUAUAzAAQAyAAA6gjQA6gjBKAAQAvAAArAUAhVq3QAIgMAagSQAcgUANAAQANAAAJAFQAJAFADAAQAAAUgBAJQgDAOgGAHIg7AAIAAgUAkdCYQgJgbgIgZAm9kTQgcAtgrA0QgZAdgyA5QhZBrgjBrQgPAtgRBvQgBAEAAADIgIA0QgBAIgBAHQgVCWguBkAsREQQg6BvjACDQgzAjhjA/QhSA3gmAjQh6ByhSB0QhfCIgzCaIgKAAAtNQwQBLhzCAgyQBzgtC2AAQBmAACVAVQDEAbAgACA7RTaQAZgBARgKQAKgGAJgFQAJgEAGgDIAAAB");
	this.shape_10.setTransform(-7.3622,23.7509);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF0000").s().p("AhgA1QgbgigMgiQgGgTgBgUQArgBApgFQgPAPgTALQATgLAPgPQAtgFAogLQABBSAJAdQgJgdgBhSQAqgKAngQIAOgFIAPgHQADAOACAOIABAIIAAADQACAwgRAvIgCAGIgDAHQgjBShHAAQg9AAg0g+g");
	this.shape_11.setTransform(59.2916,61.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#666666").s().p("Ap5WmQiLgBiAgDInCAAQhZAAhrgkQiMgvgigHIAAhkQAFgFAFgVIABgGIAPgHIAAABIAEAIIAKAAQAziaBfiIQBSh0B6hyQAmgjBSg3QBjg/AzgjQDAiDA6hvIAmAGIgBAHIgIA0IgCAPQgVCWguBkQAuhkAViWIACgPIAIg0IABgHQARhvAPgtQAjhrBZhrIBLhWQArg0AcgtIAlgIQANBHAWBPQAZBZAuCQQguiQgZhZQgWhPgNhHQgRhgAAhRQAAiIBCiWIAGgNQA1h1BUhoIAfgkQBwh/CEhJQCOhPCKAAQBpAABvBRIAJgLQBChoAjgkQBPhQBkAAQBFAABvCqQBuCoAABmQAAA2gUAkQgXAogqAAQgtAAhmg8Qhmg8gQAAQgEAAgNAHQhMhshShKQgbgYgbgUQAbAUAbAYQBSBKBMBsQAnA5AmBCQBoC1A/DJQA/DLAACZQAADLiqB/IgeAVQgiAWgkAQIgQAHIgNAGQhjgWAEh6QABgRACgUQgCAUgBARIgNAAQACA8gQAxQgQAvgdAdQgpAFgsABQABAUAHAUQALAjAcAhQA0A+A+AAQBGAAAjhSIADgHIADgGQARgvgDgwIAAgEIgBgIQgBgOgDgOQAkgQAigWQgBA+gOBuIgCARIgBADIgBALIgCARIgFAnIAFgnIACgRIABgLIABgDIACgRIAtAGID0CqQCsB6B0BmQFUEoggDIQgGADgJADIAEAIQiQAzj2AUIAAAAIgCAAIgDABQhWAHhjADIgeABQikAEoDgLQiHgCjEATQhtAKjHAXQiEAOkGAAIgTAAgAaTUWQgfAGgNAEQANgEAfgGIAVgEIgVAEgARRPtQB5B5BTCcQhTich5h5QijijiUAAQgpAAgTACQgxAEgQAOQAQgOAxgEQATgCApAAQCUAACjCjgAIlS8IABgaQAAg9gdhRQgihdgmgdQAmAdAiBdQAdBRAAA9IgBAagAqbOLQiAAyhLBzQBLhzCAgyQBzgtC2AAQBmAACVAVQDEAbAgACQgggCjEgbQiVgVhmAAQi2AAhzAtgAMzItIACgsIgCAsgAhyCmQBDAZBvAxQBiApBPASQBpAXCFAAIATAAIAAgIIABgMIgBAMIAAAIIgTAAQiFAAhpgXQhPgShigpQhvgxhDgZQhngnhugbQBuAbBnAngAk2CYIgRg0IARA0gAKCCDQAAgXgDgaQADAaAAAXgAlHBkIghgIIAhAIgAHVidQAcgGAYgIQAwgQAZgWQAtglAAhKQAAhFgUgaQgXgehDAAQhHAAgxAUQhGAcAAA+QAAAhAyBBQA2BGApAAQAOAAAJgFQAJgFAFAGQgYAIgcAGgAhasvQgyAwAAA+IAAAKQABATAFAeQAGApAIAeQAaAAA5APQA4APAoAAQBlAAAdgLQAygSAAhCQAAhegyg9Qg5hGhnAAQhEAAgzAygAKBurQhZAWg2BCQg7BHAABpQAAA3AyAZQAoAUBGAAQCgAAAAigQAAgsgXguQgHgPgKgQIgQgXQgTgagWgSQgKgJgLgHIgCgBIgBgBIAAAAQgogYgvAAIAAAAIgCAAIAAgKIAAAKIACAAIAAAAQAvAAAoAYIAAAAIABABIACABgALUvRIgjAWIAjgWIASgLIgSALgAsXrfIgThLQAAhyA7hRQBChaBuAAQA6AABmAnQBuAvAtAOIATAPQhUBog1B1IgMgGQgrgUgvAAQhKAAg6AjQg6AjgyAAQgzAAgUgUg");
	this.shape_12.setTransform(-4.8622,23.7509);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},4).to({state:[{t:this.shape_9},{t:this.shape_5},{t:this.shape_8},{t:this.shape_7}]},5).to({state:[{t:this.shape_12},{t:this.shape_5},{t:this.shape_11},{t:this.shape_10}]},4).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-184.5,-123.3,354.3,294.2);


// stage content:
(lib.Kang_newHaiku = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {artwork:1};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,1];
	// timeline functions:
	this.frame_0 = function() {
		var root = this;
		stage.enableMouseOver();
		
		this.line01_txt.addEventListener("click", changeLine01);
		function changeLine01(){
		    console.log("will change line 1");
		    root.line01_txt.text = line01;
		}
		var line01 = "I am Yeogu ";
		
		this.line02_txt.addEventListener("click", changeLine02);
		function changeLine02(){
		    console.log("will change line 2");
		    root.line02_txt.text = line02;
		}
		var line02 = "KOREA";
		
		this.line03_txt.addEventListener("click", changeLine03);
		function changeLine03(){
		    console.log("will change line 3");
		    root.line03_txt.text = line03;
		}
		var line03 = "There he is";
		
		var root = this;
		stage.enableMouseOver();
		this.stop();
		
		this.toFrame02_btn.addEventListener("click", toFrame02);
		
		function toFrame02() {
		    console.log("Moving to Frame 2");
			root.gotoAndStop("artwork");
		}
	}
	this.frame_1 = function() {
		this.stop();
		var root = this;
		stage.enableMouseOver();
		
		this.toFrame01_btn.addEventListener("click", toFrame01);
		
		function toFrame01() {
		    console.log("going to frame 1");
		    root.gotoAndStop(0);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// buttons
	this.toFrame02_btn = new lib.ciclebutton();
	this.toFrame02_btn.name = "toFrame02_btn";
	this.toFrame02_btn.setTransform(449.7,477.05);
	new cjs.ButtonHelper(this.toFrame02_btn, 0, 1, 2, false, new lib.ciclebutton(), 3);

	this.toFrame01_btn = new lib.flagbutton();
	this.toFrame01_btn.name = "toFrame01_btn";
	this.toFrame01_btn.setTransform(461.9,129.85);
	new cjs.ButtonHelper(this.toFrame01_btn, 0, 1, 2, false, new lib.flagbutton(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.toFrame02_btn}]}).to({state:[{t:this.toFrame01_btn}]},1).wait(1));

	// dog
	this.instance = new lib.carl();
	this.instance.setTransform(286.6,437.7,1,1,0,0,0,19,-46);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

	// who
	this.instance_1 = new lib.myself();
	this.instance_1.setTransform(639.05,466.6,1,1,0,0,0,18.7,-67.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(1));

	// text
	this.line03_txt = new cjs.Text("Where is my dog", "bold 40px 'Arial'");
	this.line03_txt.name = "line03_txt";
	this.line03_txt.textAlign = "center";
	this.line03_txt.lineHeight = 47;
	this.line03_txt.lineWidth = 659;
	this.line03_txt.parent = this;
	this.line03_txt.setTransform(471.9,224.7);

	this.line02_txt = new cjs.Text("Where am I", "bold 40px 'Arial'");
	this.line02_txt.name = "line02_txt";
	this.line02_txt.textAlign = "center";
	this.line02_txt.lineHeight = 47;
	this.line02_txt.lineWidth = 659;
	this.line02_txt.parent = this;
	this.line02_txt.setTransform(471.9,157.45);

	this.line01_txt = new cjs.Text("Who am I", "bold 40px 'Arial'");
	this.line01_txt.name = "line01_txt";
	this.line01_txt.textAlign = "center";
	this.line01_txt.lineHeight = 47;
	this.line01_txt.lineWidth = 659;
	this.line01_txt.parent = this;
	this.line01_txt.setTransform(471.9,90.45);

	this.text = new cjs.Text("Yeogu Kang", "bold 40px 'Arial'");
	this.text.textAlign = "center";
	this.text.lineHeight = 47;
	this.text.parent = this;
	this.text.setTransform(473.75,20.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.text},{t:this.line01_txt},{t:this.line02_txt},{t:this.line03_txt}]}).to({state:[]},1).wait(1));

	// background
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(5,1,1).p("EhNjg0JMCbHAAAMAAABoTMibHAAAg");
	this.shape.setTransform(485.425,324.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,598.2).s().p("EhNjA0KMAAAhoTMCbHAAAMAAABoTg");
	this.shape_1.setTransform(485.425,324.425);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1,1,1).p("EhEMA5vIuvAAMAAAhzdMCl3AAAMAAABzdIneAAg");
	this.shape_2.setTransform(478.075,336.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,646.8).s().p("EBLeA5vMAAAgyrMiPqAAAMAAAAyrIuvAAMAAAhzdMCl3AAAMAAABzdgEhEMA5vMAAAgyrMCPqAAAMAAAAyrg");
	this.shape_3.setTransform(478.075,336.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(426.3,285.8,583.5999999999999,421.09999999999997);
// library properties:
lib.properties = {
	id: 'FA16C407DE3DC940A564333FE01563F7',
	width: 960,
	height: 640,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['FA16C407DE3DC940A564333FE01563F7'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;